version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: youlytic_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/0
      YOUTUBE_API_KEY: AIzaSyBRtIjCIBjklW6mBxYpeT8VBhoebWuvA9c
      RAILS_ENV: development
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app

  sidekiq:
    build: .
    command: bundle exec sidekiq
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/0
      YOUTUBE_API_KEY: AIzaSyBRtIjCIBjklW6mBxYpeT8VBhoebWuvA9c
      RAILS_ENV: development
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app

volumes:
  postgres_data:
  redis_data: