app = "youlytic2-sns"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile.fly"

[env]
  RAILS_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"

[deploy]
  release_command = "bundle exec rails db:create db:migrate || true"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512